server:
  port: 9007
spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
service-url:
  nacos-user-service: http://nacos-payment-provider #区分大小写