server:
port: 8803
spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 47.102.197.42
                port: 5672
                username: guest
                password: guest

      bindings:
        input:
          destination: studyExchange
          content-type: application/json
          binder: defaultRabbit
          group: cloudA


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http:localhost:7002/eureka,http:localhost:7003/eureka
  instance:
    instance-id: receive-8803.com  # 在信息列表时显示主机名称
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
    lease-renewal-interval-in-seconds:  2 # 设置心跳的时间间隔（默认是30秒）
    prefer-ip-address: true